### PR TITLE
GPU feature describer fixes.

### PR DESCRIPTION
**Pull request by donlk**
Relevant discussion: #10 
Let me know if it conflicts with your cereal version.

### CODE REVIEW

**Comment by mdaiter** [comment]
Hey @donlk , I think this conflicts with my cereal version. Let me update it in a day or two and get back to this

**Comment by pmoulon** [comment]
You can update the cereal submodule to https://github.com/openMVG-thirdparty/cereal/tree/069d0faa9be1927a63ec13d4247ded74ba832183 or cherry pick this commit https://github.com/openMVG/openMVG/commit/ff22ff265da0789b785fca9206b812a04c844c6e

**Comment by mdaiter** [comment]
@pmoulon updated it! Let me merge.

**Comment by mdaiter** [comment]
@donlk thank you!

**Comment by mdaiter** [comment]
@donlk now I seem to be getting bugs on your commit.
`In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:17:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:47:98: error: expected constructor, destructor, or type conversion before ‘;’ token
 CEREAL_REGISTER_POLYMORPHIC_RELATION(openMVG::features::Regions, openMVG::features::SIFT_Regions);
                                                                                                  ^
In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:44:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:17,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/home/nomoko/Code/custom/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:100:3: error: expected constructor, destructor, or type conversion before ‘namespace’
   namespace cereal {                                         \
   ^
/home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:50:1: note: in expansion of macro ‘CEREAL_REGISTER_TYPE_WITH_NAME’
 CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Liop_Regions, "AKAZE_Liop_Regions");
 ^
In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/image/image.hpp:29:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/akaze/AKAZE.hpp:35,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/image_describer_akaze.hpp:15,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:19,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/home/nomoko/Code/custom/openMVG/src/openMVG/image/image_convolution.hpp:207:45: error: expected declaration before end of line
In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:17:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG_Samples/features_affine_demo/features_affine_demo.cpp:8:
/home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:47:98: error: expected constructor, destructor, or type conversion before ‘;’ token
 CEREAL_REGISTER_POLYMORPHIC_RELATION(openMVG::features::Regions, openMVG::features::SIFT_Regions);
                                                                                                  ^
`
Thoughts?

**Comment by donlk** [comment]
It seems you're using the old region classes, hence `SIFT_Regions` and  `AKAZE_Liop_Regions` are not present. Sending a fix for that later today.

**Comment by mdaiter** [comment]
@donlk I'm on it

**Comment by mdaiter** [comment]
@donlk it seems that the issue is here:
`In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:44:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:17,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/home/nomoko/Code/custom/openMVG/src/dependencies/cereal/include/cereal/types/polymorphic.hpp:100:3: error: expected constructor, destructor, or type conversion before ‘namespace’
   namespace cereal {                                         \
   ^
/home/nomoko/Code/custom/openMVG/src/openMVG/features/regions_factory.hpp:48:1: note: in expansion of macro ‘CEREAL_REGISTER_TYPE_WITH_NAME’
 CEREAL_REGISTER_TYPE_WITH_NAME(openMVG::features::AKAZE_Float_Regions, "AKAZE_Float_Regions");
 ^
In file included from /home/nomoko/Code/custom/openMVG/src/openMVG/image/image.hpp:29:0,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/akaze/AKAZE.hpp:35,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/image_describer_akaze.hpp:15,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/features/features.hpp:19,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/indMatchDecoratorXY.hpp:13,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.hpp:12,
                 from /home/nomoko/Code/custom/openMVG/src/openMVG/matching/regions_matcher.cpp:8:
/home/nomoko/Code/custom/openMVG/src/openMVG/image/image_convolution.hpp:207:45: error: expected declaration before end of line
`

**Comment by mdaiter** [comment]
@donlk fixed it! Turns out Cereal didn't get updated.
Also, I needed to take out imagery from being privatised. In an effort to launch off individual image_describer_X.hpp processes with isolated pure functions, I've gone ahead and launched off isolated imageGray objects. In the future, I plan on making that a const variable so it can be safely passed around to different image describers.

**Pull request merged**
